@startuml
class User{
   -int id
   -bool isWork
   -QString lastName
   -QString firstName
   -QString patronymic
   -QString address
   -QString phone
   -QString branch
   -QString login
   -QString password
   -int role
}

class Contract{
   -int id
   -Date date
   -double insuranceSum
   -int typeInsurance
   -double tariffRate
   -int idClient
   -int idEmployee
   -int status
   -int idConfirmedAccountant
}

class ProfileWindow{
   User user
   void Logout()
}

class  LoginWindow{
   QString login
   QString password
   Database db
   void checkUser()
}

class ContractConclusionWindow{
   Contract contractData
   void ConcludeContract()
}

class ContractRenegotiateWindow{
   AgentModel model
   TableView view
   Contract contractData
   void sendContract()
}

class AgentStatisticsWindow{
   TableView view
   AgentModel model
   void sort()
}

class AbstractWindowForRole{
   ProfileWindow profile
   SidePanel notify
   void SetUser()
   void ShowProfileWindow()
}

class WindowNavigator{
   -AbstractWindowForRole WindowForRole
   -LoginWindow login
}

class Database {
   +void CreateTables()
   +Contract GetContractById()
   +User GetUserById()
   +bool ChangeContract()
   +bool UserVerify()
   +bool AddUser()
   +bool AddContract()
   +bool ChangeUser()
   +bool ConfirmationContract()
   +bool RenegotiateContract()
}

class AgentWindow{
   Database database
   ContractConclusionWindow conclusionWindow
   ContractRenegotiateWindow renegotiateWindow
   StatisticsWindow statisticsWindow
   void ShowContractConclusionWindow()
   void ShowContractRenegotiateWindow()
   void ShowStatisticsWindow()
}

class AgentModel{
   Vector<Contract> contracts
   void AddContract()
   Contract GetContract(int index)
}

AbstractWindowForRole <|-- AgentWindow
AgentWindow o-- Database
WindowNavigator --> AbstractWindowForRole
WindowNavigator --> LoginWindow
AgentWindow --> ContractConclusionWindow
AgentWindow --> ContractRenegotiateWindow
AgentWindow --> AgentStatisticsWindow
AgentStatisticsWindow --> AgentModel
AbstractWindowForRole --> ProfileWindow
AgentModel --> Contract
ProfileWindow --> User


ContractConclusionWindow --> Contract
ContractRenegotiateWindow --> Contract
ContractRenegotiateWindow --> AgentModel

LoginWindow o-- Database

@enduml