@startuml
class User{
   -int id
   -bool isWork
   -QString lastName
   -QString firstName
   -QString patronymic
   -QString address
   -QString phone
   -QString branch
   -QString login
   -QString password
   -int role
}

class Contract{
   -int id
   -Date date
   -double insuranceSum
   -int typeInsurance
   -double tariffRate
   -int idClient
   -int idEmployee
   -int status
   -int idConfirmedAccountant
}

class ProfileWindow{
   User user
   void Logout()
}

class  LoginWindow{
   QString login
   QString password
   Database db
   void checkUser()
}

class TariffRateWindow{
   double rateOne
   double rateTwo
   double rateThree
   void SetRate()
   void GetRate()
}

class ContractConfirmationWindow{
   AccountantModel model
   TableView view
   Contract contractToConfirm
   void ConfirmContract()
   void NotConfirmContract()
}

class AccountantStatisticsWindow{
   TableView view
   AccountantModel model
   void sort()
}

class AbstractWindowForRole{
   ProfileWindow profile
   SidePanel notify
   void SetUser()
   void ShowProfileWindow()
}

class WindowNavigator{
   -AbstractWindowForRole WindowForRole
   -LoginWindow login
}

class Database {
   +void CreateTables()
   +Contract GetContractById()
   +User GetUserById()
   +bool ChangeContract()
   +bool UserVerify()
   +bool AddUser()
   +bool AddContract()
   +bool ChangeUser()
   +bool ConfirmationContract()
   +bool RenegotiateContract()
}

class AccountantWindow{
   Database database
   StatisticsWindow statisticsWindow
   TariffRateWindow tariffRate
   ContractConfirmationWindow confirmWindow
   void ShowStatisticsWindow()
   void ShowContractConfirmationWindow()
   void ShowTariffRateWindow()
}

class AccountantModel{
   Vector<Contract> contracts
   void AddContract()
   Contract GetContract(int index)
}


AbstractWindowForRole <|-- AccountantWindow
AccountantWindow o-- Database
WindowNavigator --> AbstractWindowForRole
WindowNavigator --> LoginWindow
AccountantWindow --> ContractConfirmationWindow
AccountantWindow --> TariffRateWindow
AccountantWindow --> AccountantStatisticsWindow
AccountantStatisticsWindow --> AccountantModel
AbstractWindowForRole --> ProfileWindow
AccountantModel --> Contract
ProfileWindow --> User

ContractConfirmationWindow --> Contract
ContractConfirmationWindow --> AccountantModel

LoginWindow o-- Database

@enduml