@startuml
skinparam Shadowing true
actor "Агент" as agent
boundary "Главное меню\nагента" as mainMenuAg
boundary "Окно заключения\n  договора" as contractWindow 
boundary "Окно ошибки" as errorWindow #Red

entity "База данных" as fs

agent -> mainMenuAg:Нажал заключить\n договор
mainMenuAg -> contractWindow:Отобразить
contractWindow --> agent
agent -> contractWindow : Вводит данные
contractWindow -> contractWindow : Проверка\n данных

alt Данные корректны
    contractWindow -> fs : Запись в базу
    fs --> contractWindow
    contractWindow --> agent
else Данные не корректны
    contractWindow -> errorWindow : Создать
    errorWindow --> agent
end

@enduml