@startuml
skinparam Shadowing true
actor "Агент" as agent
boundary "Вкладка заключения\n  договора" as contractWindow 
boundary "Окно ошибки" as errorWindow #Red

entity "Файловая система" as fs

agent -> contractWindow : Вводит данные
contractWindow -> contractWindow : Проверка\n данных

alt Данные корректны
    contractWindow -> fs : Запись в базу
    fs --> contractWindow
    contractWindow --> agent
else Данные не корректны
    contractWindow -> errorWindow : Создать
    errorWindow --> agent
end

@enduml