@startuml
skinparam Shadowing true
actor "Агент" as agent
boundary "Главное меню\n  агента" as mainMenuAg
boundary "Окно выбора\n   договора" as contractWindow
boundary "Окно перезаключения\n  договора" as reContractWindow
boundary "Окно ошибки" as errorWindow #Red

entity "Файловая система" as fs

agent -> mainMenuAg : Нажал перезаключить\n\tдоговор
mainMenuAg -> contractWindow : Отобразить
contractWindow -> reContractWindow : Отобразить
reContractWindow --> agent
agent -> reContractWindow : Вводит данные
reContractWindow -> reContractWindow : Проверка\n данных

alt Данные корректны
    reContractWindow -> fs : Обновление базы
    fs --> reContractWindow
    reContractWindow --> agent
else Данные не корректны
    reContractWindow -> errorWindow : Создать
    errorWindow --> agent
end
@enduml