@startuml
skinparam Shadowing true
actor "Бухгалтер" as accountant
boundary "Главное меню\nбухгалтера" as mainMenuAc
boundary "Окно просмотра\nстатистики" as statisticWindow 

entity "База данных" as fs

accountant -> mainMenuAc:Нажал просмотреть\nстатистику
mainMenuAc -> statisticWindow:Отобразить
statisticWindow -> fs:Запрос к БД
fs --> statisticWindow
statisticWindow -> statisticWindow:Обработка\n запроса
statisticWindow --> accountant
@enduml