@startuml
skinparam Shadowing true
actor "Администратор" as admin
boundary "Главное меню\nадминистратора" as mainMenuAd
boundary "Окно управления\nпользователями" as changeUserTab
boundary "Окно редактирования\nпользователя" as changeUserWindow
boundary "Окно ошибки" as errorWindow #Red 

entity "База данных" as fs

admin -> mainMenuAd:Нажал управление\n пользователями
mainMenuAd -> changeUserTab:Отобразить
changeUserTab -> fs:Чтение данных
fs --> changeUserTab
changeUserTab --> admin
admin -> changeUserTab:Выбрал пользователя
changeUserTab -> changeUserWindow :Отобразить
changeUserWindow --> admin
admin -> changeUserWindow:Вводит данные
changeUserWindow -> changeUserWindow:Проверка\n данных
alt Данные корректны
    changeUserWindow -> fs:Обновление БД
    fs --> changeUserWindow
    changeUserWindow --> admin
else Данные не корректны
    changeUserWindow -> errorWindow : Создать
    errorWindow --> admin
end

@enduml