@startuml
skinparam Shadowing true
actor "Администратор" as admin
boundary "  Главное меню\nадминистратора" as mainMenuAd
boundary "Окно удаления\n пользователей" as removeUserWindow 

entity "Файловая система" as fs

admin -> mainMenuAd : Нажал удалить\n пользователя
mainMenuAd -> removeUserWindow : Отобразить
removeUserWindow --> admin
admin -> removeUserWindow : Выбирает пользователя
removeUserWindow -> fs : Обновить базу
fs --> removeUserWindow
removeUserWindow --> admin

@enduml