@startuml
skinparam Shadowing true
actor "Агент" as agent
boundary "Вкладка заключения\n         договора" as contractWindow 
boundary "Окно ошибки" as errorWindow #Red

control "Обновление базы\n         данных" as updateDatabase
control "Проверка корректности\n             данных" as checkCorrectData
control "Открытие окна\n       ошибки" as errorWindowControl
entity "Файловая система" as fs

contractWindow -l-> checkCorrectData
checkCorrectData --> errorWindowControl
errorWindowControl --> errorWindow
checkCorrectData --> updateDatabase 
updateDatabase <--> fs

agent -- contractWindow
agent -- errorWindow
@enduml

