@startuml
skinparam Shadowing true
actor "Администратор" as admin
boundary "Главное меню администратора" as mainMenuAd
boundary "Окно редактирования\n      пользователей" as changeUserTab
boundary "Окно редактирования\n      пользователя" as changeUserWindow

control "             Открытие окна\nредактирования пользователей" as changeUserTabControl
control "Открытие окна редактирования\n               пользователя" as changeUserWindowControl
control "Обновление базы\n         данных" as writeToDatabase
entity "База данных" as fs

control "Проверка корректности\n              данных" as checkControl
control "Чтение данных" as readData
boundary "Окно ошибки" as errorWindow #Red

admin -u- mainMenuAd
mainMenuAd --> changeUserTabControl
changeUserTabControl --> changeUserTab
changeUserTab --> changeUserWindowControl :Выбран \nпользователь
changeUserWindowControl --> changeUserWindow
changeUserWindow --> checkControl
checkControl --> errorWindow
checkControl --> writeToDatabase
writeToDatabase --> fs
changeUserTab --> readData
readData --> fs
admin -- changeUserTab
admin -- changeUserWindow
admin -- errorWindow

@enduml

removeUserWindowControl --> removeUserWindow 
removeUserWindow --> checkControl 
checkControl --> writeToDatabase
checkControl --> errorWindow
errorWindow -- admin

writeToDatabase --> fs
admin -- removeUserWindow 