@startuml

left to right direction

actor "Агент" as fc

usecase "Войти в систему" as UC1
usecase "Заключить договор" as UC2
usecase "Просмотреть статистику\n по договорам" as UC3
usecase "Перезаключить договор" as UC4

fc --> UC1
fc --> UC2
fc --> UC3
fc --> UC4

@enduml